<a href="https://colab.research.google.com/github/Argivist/Python-Package-Tutorial-and-Guidebooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy is a python package commonly used for mathematical and scientific compyting. from simple mathematical operations like addition to matrix operation


## Getting Started
To get started you will need to install the numpy package *if you havent already*

In [137]:
!pip install numpy

then in your notebook or pthon file simpy import it.
```import numpy```
you can assign a custom name to the package you use by attaching ``` as custom_name ```
to the import. this becomes the name you reference the numpy package.



In [138]:
import numpy as np

you will notice in my code extracts from below i use np to refer to numpy

## Arrays and attributes
An array is a collection of data of varying shape.


### Array vs list in python
Python has a list object which acts similarly however there is a distinct difference. in pthon lists can hod itemms of varying types whilst arrays can onl hold one type

In [139]:
l=[1,"hello"]
list_type=type(l)
first_item=type(l[0])
last_item=type(l[1])
print( f"The type of the list is {list_type}\nThe type of the first object is {first_item}\nThe type of the last object is {last_item}")

The type of the list is <class 'list'>
The type of the first object is <class 'int'>
The type of the last object is <class 'str'>


in this code you would notice the items in the list have different types integers, aand string

In [140]:
l=np.array([1,"hello"])
list_type=type(l)
first_item=type(l[0])
last_item=type(l[1])
print( f"The type of the list is {list_type}\nThe type of the first object is {first_item}\nThe type of the last object is {last_item}")

The type of the list is <class 'numpy.ndarray'>
The type of the first object is <class 'numpy.str_'>
The type of the last object is <class 'numpy.str_'>


because arrays hold itmes of the same type you can use ```.dtype``` to check the type of the items

In [141]:
l.dtype

dtype('<U21')

In [142]:
l2=np.array([1,2,3,4])
l2.dtype

dtype('int64')

if you look at this result however you notice unlike the list impelemntation before, all the objects are converted to the same type

### Creating an array
to create an array you use `.array()` from the numpy package and place a list as an argument
i.e.
```
array=np.array(list)
```

e.g.

In [143]:
array=np.array([1,2,3,4])

or you can create a list separately and convert it into an array after
e.g.

In [144]:
list=['a','b','c']
array=np.array(list)

you can also use .size so check the number of items in an array

In [145]:
array.size

3

**Task:**
create an array containing the first 4 fibronaci numbers _you can look them up_

In [146]:
## you can work here

**Shape**

Arrays have shapes/dimensions.

The shape of an array defines its structure along each axis (dimension). It is represented as a Python tuple of integers.

1D Array (Vector): Has one dimension. Shape is (n,).

2D Array (Matrix): Has two dimensions. Shape is (rows, columns).

3D Array (Tensor): Has three dimensions. Shape is (depth, rows, columns).

you can have arrays that are 4D, 5D, and soo much more.

```.shape``` shows the shape of an array

In [147]:
array.shape

(3,)

In [148]:
array2=np.array([[1,2,3],[2,3,4]])# a 2D array of shape 2x3
array2.shape

(2, 3)

In [149]:
array3=np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,5]]])# a 3D array of shape 2x2x3
array3.shape

(2, 2, 3)

### Generating arrays
Sometimes you would want to create arrays without giving the values yourself this is where ```.zeros(), .ones(),.arange()``` come in

```.zeros(shape)``` generates an arrray of a given shape consisting only of 0s it takes a tuple of a shape ie (size,size,size) as an argument

In [150]:
zero_list=np.zeros((2,3,4))
zero_list

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

```.ones(shape)``` generates an arrray of a given shape consisting only of 1s it takes a tuple of a shape ie (size,size,size) as an argument

In [151]:
one_list=np.ones((1,2,3))
one_list

array([[[1., 1., 1.],
        [1., 1., 1.]]])

```.arange(start,stop,step)``` Generates a 1D array with evenly spaced values based on your parameters.

```start```: The first value in the array (inclusive).

```stop```: The end boundary (exclusive—the array stops before reaching this value).

```step```: The spacing between each consecutive value.

In [152]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

```.linspace(start,stop,step)``` Generates a 1D array of num evenly spaced samples over a specified interval.

```start```: The first value in the sequence.

```stop```: The final value (inclusive—unlike arange, the endpoint is included).

```n```: The number of samples to generate (defaults to 50).

In [153]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

take a close look at both arange and linspace and try to spot the difference

### random generation
you can also randomly generate arrays

In [178]:
# 1. ALWAYS set a seed for reproducibility during tutorials/debugging
np.random.seed(42)

# 2. Uniform [0, 1)
u = np.random.rand(3, 2)  # 3 rows, 2 cols

# 3. Normal (Gaussian)
n = np.random.randn(3, 2) # 3 rows, 2 cols, centered at 0

# 4. Custom Integers
ints = np.random.randint(1, 100, size=5) # 5 random ints between 1 and 99

print("Uniform (0-1):\n", u)
print("\nNormal (Bell Curve):\n", n)
print("\nIntegers:\n", ints)

Uniform (0-1):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]

Normal (Bell Curve):
 [[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]

Integers:
 [76 58 22 89 49]


if you want to get a sectino of the array you can use ```arr[i,j]``` for a one dinetional array where i is the first index and j is the last index you want to access this is called ***_slicing_***


In [154]:
arr[2:5]

array([3])





## Manipulation and Reshaping

Sometimes you would want to alter the shape of the arrays.

lets take the array below

In [155]:
arr=np.arange(1,23,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22])

```.reshape(r,c)```

Changes the layout of an array without changing its actual data or total number of elements.

r: The new number of rows.

c: The new number of columns.

***WARNING:*** If the product of your new dimensions ```row x column``` does not match the original .size, NumPy will raise a ValueError.

In [156]:
arr.reshape(3,3,3) #3x3x3=27 which is not equal to 8


ValueError: cannot reshape array of size 8 into shape (3,3,3)

In [157]:
arr.reshape(2,4) # 2x4=8

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [159]:
arr.reshape(2,2,2) #2x2x2=8

array([[[ 1,  4],
        [ 7, 10]],

       [[13, 16],
        [19, 22]]])

```.flatten()```: converts any array into a 1D array

In [160]:
arr.flatten
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22])

you can stack arrays on each other in both veritcal and hprizonntal shapes

In [161]:
arr1=np.arange(1,10,3)
arr1

array([1, 4, 7])

In [162]:
arr2=np.arange(11,20,3)
arr2

array([11, 14, 17])

In [163]:
np.hstack((arr1,arr2))

array([ 1,  4,  7, 11, 14, 17])

In [164]:
np.vstack((arr1,arr2))

array([[ 1,  4,  7],
       [11, 14, 17]])

these can also be used to reshape arrays

In [165]:
np.vstack(arr1)

array([[1],
       [4],
       [7]])

In [166]:
np.hstack(arr1)

array([1, 4, 7])

## Broadcasting and vectorization

Broadcasting allows NumPy to perform arithmetic on arrays of different shapes by "stretching" the smaller array to match the larger one.

In [167]:
a = np.array([1, 2, 3])
b = 2
print(a,"*",b,"=",a * b)                # [2, 4, 6] (Broadcasting scalar 2)


[1 2 3] * 2 = [2 4 6]


In [168]:

mat = np.array([[1], [2]])
print(mat,"+",a,"=",mat + a)              # Adds [1,2,3] to both rows [1] and [2]

[[1]
 [2]] + [1 2 3] = [[2 3 4]
 [3 4 5]]


## Mathematical & Statistical Methods (Axes)
Operations often need to be performed across specific dimensions. Understanding axis is the #1 hurdle for beginners.

In [169]:
a=np.array([[1,2,3],[4,5,6]])

```.sum()``` gives the sumoof all items in the array given they are integers, floats or any numerical datatype

In [170]:
a.sum()

np.int64(21)

```.mean()``` gives the average/mean of the items in the array

In [171]:
a.mean()

np.float64(3.5)

```np.argmac(array)``` gives the maximum index an array has

In [172]:
np.argmax(a)

np.int64(5)

these operations are done accross the entire array but if ou would like to apply it columnwise, row wiise or on a specific axis you specify that axis

```axis=0,1,etc```

In [173]:
a.mean(axis=0)# mean of (1,4),(2,5)and (3,6)

array([2.5, 3.5, 4.5])

In [174]:
a.sum(axis=1) #sum of (1,2,3),(4,5,6)

array([ 6, 15])

## Memory Managing

Crucial for avoiding bugs where modifying a slice unexpectedly changes the original array.

- **View**: Slicing creates a view. Modifying the slice modifies the original.

- **Copy**: ```.copy()``` creates a new object. Modifying it does not touch the original.

In [175]:
arr = np.array([1, 2, 3])
view = arr[0:2]             # This is a view
view[0] = 99
print(arr)

[99  2  3]


In [176]:
arr = np.array([1, 2, 3])
copy = arr[0:2].copy()      # This is a copy
copy[0] = 5
print(arr)

[1 2 3]


## Practice Task

### **Scenario**:
You are an engineer testing a new temperature sensor. You have 24 hours of readings (one per hour), but the sensor is "noisy." You need to clean the data, find the peaks, and normalize the results for a report.

### The Task:
**Generate Data**: Create a 1D array of 24 hourly readings starting at 20.0°C and ending at 35.0°C using np.linspace.

**Add Noise:** Create a second array of 24 random "noise" values between -1.5 and 1.5 using np.random.uniform.

**Apply Vectorization:** Add the noise array to your temperature array to create raw_readings.

**Analyze:**

Find the Mean and Standard Deviation of the readings.

Find the Hour (index) where the temperature was at its Maximum.

**Filter (Boolean Indexing):** Create a new array called high_temps that only contains readings greater than 30.0°C.

**Reference Check:** Print the Shape of your raw_readings and your high_temps to see how many hours exceeded the threshold.

## Reference

[Numpy Documentation](https://numpy.org/doc/stable/)